[build]
  base = "client"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"
  VITE_API_URL = "https://budgetbuddy-lgty.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 