# This is the root level netlify.toml
# It instructs Netlify to use the client directory

[build]
  base = "client"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://budgetbuddy-lgty.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 