services:
  - type: web
    name: budget-buddy-api
    env: node
    plan: free
    buildCommand: chmod +x deployment-fix.sh && ./deployment-fix.sh
    startCommand: node server.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d
      - key: CLIENT_URL
        value: https://budgetbuddy.vercel.app 